### ISSUE TITLE
Support for HIP Objects

### ISSUE THREAD

**Issue by cdot65** [cdot65/pan-scm-sdk#71]
OpenAPI schema:

path information:

```yaml
  /hip-objects:
    get:
      tags:
        - HIP Objects
      summary: List HIP objects
      description: |
        Retrieve a list HIP objects.
      operationId: ListHIPObjects
      parameters:
        - $ref: '#/components/parameters/name'
        - $ref: '#/components/parameters/folder'
        - $ref: '#/components/parameters/snippet'
        - $ref: '#/components/parameters/device'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    allOf:
                      - type: array
                        items:
                          $ref: '#/components/schemas/hip-objects'
                  limit:
                    type: number
                    default: 200
                  offset:
                    type: number
                    default: 0
                  total:
                    type: number
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        default:
          $ref: '#/components/responses/default_errors'
    post:
      tags:
        - HIP Objects
      summary: Create a HIP object
      description: |
        Create a new HIP object.
      operationId: CreateHIPObjects
      requestBody:
        description: Created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hip-objects'
      responses:
        '201':
          $ref: '#/components/responses/http_created'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
  '/hip-objects/{id}':
    get:
      tags:
        - HIP Objects
      summary: Get a HIP object
      description: |
        Get an existing HIP object.
      operationId: GetHIPObjectsByID
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hip-objects'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        default:
          $ref: '#/components/responses/default_errors'
    put:
      tags:
        - HIP Objects
      summary: Update a HIP object
      description: |
        Update an existing HIP object.
      operationId: UpdateHIPObjectsByID
      parameters:
        - $ref: '#/components/parameters/uuid'
      requestBody:
        description: OK
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hip-objects'
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic_with_body'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
    delete:
      tags:
        - HIP Objects
      summary: Delete a HIP object
      description: |
        Delete a HIP object.
      operationId: DeleteHIPObjectsByID
      parameters:
        - $ref: '#/components/parameters/uuid'
      responses:
        '200':
          $ref: '#/components/responses/http_ok'
        '400':
          $ref: '#/components/responses/bad_request_errors_basic'
        '401':
          $ref: '#/components/responses/auth_errors'
        '403':
          $ref: '#/components/responses/access_errors'
        '404':
          $ref: '#/components/responses/not_found'
        '409':
          $ref: '#/components/responses/conflict_errors'
        default:
          $ref: '#/components/responses/default_errors'
```

schema:

```yaml
    hip-objects:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: UUID of the resource
          readOnly: true
          example: 123e4567-e89b-12d3-a456-426655440000
        name:
          type: string
          pattern: ^[ a-zA-Z\d.-_]+$
          description: The name of the HIP object
          maxLength: 31
        description:
          type: string
          maxLength: 255
        host_info:
          type: object
          properties:
            criteria:
              type: object
              properties:
                domain:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                os:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: object
                          oneOf:
                            - type: object
                              title: Microsoft
                              properties:
                                Microsoft:
                                  type: string
                                  description: Microsoft vendor
                                  maxLength: 255
                                  default: All
                              required:
                                - Microsoft
                            - type: object
                              title: Apple
                              properties:
                                Apple:
                                  type: string
                                  description: Apple vendor
                                  maxLength: 255
                                  default: All
                              required:
                                - Apple
                            - type: object
                              title: Google
                              properties:
                                Google:
                                  type: string
                                  description: Google vendor
                                  maxLength: 255
                                  default: All
                              required:
                                - Google
                            - type: object
                              title: Linux
                              properties:
                                Linux:
                                  type: string
                                  description: Linux vendor
                                  maxLength: 255
                                  default: All
                              required:
                                - Linux
                            - type: object
                              title: Other
                              properties:
                                Other:
                                  type: string
                                  description: Other vendor
                                  maxLength: 255
                              required:
                                - Other
                      required:
                        - contains
                client_version:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                host_name:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                host_id:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                managed:
                  type: boolean
                  description: If device is managed
                serial_number:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
          required:
            - criteria
        network_info:
          type: object
          properties:
            criteria:
              type: object
              properties:
                network:
                  type: object
                  oneOf:
                    - type: object
                      title: is
                      properties:
                        is:
                          type: object
                          oneOf:
                            - type: object
                              title: wifi
                              properties:
                                wifi:
                                  type: object
                                  properties:
                                    ssid:
                                      type: string
                                      description: SSID
                                      pattern: .*
                                      maxLength: 1023
                            - type: object
                              title: mobile
                              properties:
                                mobile:
                                  type: object
                                  properties:
                                    carrier:
                                      type: string
                                      pattern: .*
                                      maxLength: 1023
                            - type: object
                              title: unknown
                              properties:
                                unknown:
                                  type: object
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: object
                          oneOf:
                            - type: object
                              title: wifi
                              properties:
                                wifi:
                                  type: object
                                  properties:
                                    ssid:
                                      type: string
                                      description: SSID
                                      pattern: .*
                                      maxLength: 1023
                            - type: object
                              title: mobile
                              properties:
                                mobile:
                                  type: object
                                  properties:
                                    carrier:
                                      type: string
                                      pattern: .*
                                      maxLength: 1023
                            - type: object
                              title: ethernet
                              properties:
                                ethernet:
                                  type: object
                            - type: object
                              title: unknown
                              properties:
                                unknown:
                                  type: object
        patch_management:
          type: object
          properties:
            criteria:
              type: object
              properties:
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                is_enabled:
                  enum:
                    - 'no'
                    - 'yes'
                    - not-available
                  description: is enabled
                missing_patches:
                  type: object
                  properties:
                    severity:
                      type: object
                      oneOf:
                        - type: object
                          title: greater_equal
                          properties:
                            greater_equal:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - greater_equal
                        - type: object
                          title: greater_than
                          properties:
                            greater_than:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - greater_than
                        - type: object
                          title: is
                          properties:
                            is:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - is
                        - type: object
                          title: is_not
                          properties:
                            is_not:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - is_not
                        - type: object
                          title: less_equal
                          properties:
                            less_equal:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - less_equal
                        - type: object
                          title: less_than
                          properties:
                            less_than:
                              type: integer
                              minimum: 0
                              maximum: 100000
                          required:
                            - less_than
                    patches:
                      type: array
                      items:
                        type: string
                        description: patch security-bulletin-id or kb-article-id
                        pattern: .*
                        maxLength: 1023
                    check:
                      enum:
                        - has-any
                        - has-none
                        - has-all
                      default: has-any
                  required:
                    - check
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    description: Product name
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        data_loss_prevention:
          type: object
          properties:
            criteria:
              type: object
              properties:
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                is_enabled:
                  enum:
                    - 'no'
                    - 'yes'
                    - not-available
                  description: is enabled
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    description: Product name
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        firewall:
          type: object
          properties:
            criteria:
              type: object
              properties:
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                is_enabled:
                  enum:
                    - 'no'
                    - 'yes'
                    - not-available
                  description: is enabled
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                description: Product name
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        anti_malware:
          type: object
          properties:
            criteria:
              type: object
              properties:
                virdef_version:
                  type: object
                  oneOf:
                    - type: object
                      title: within
                      properties:
                        within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: versions
                              properties:
                                versions:
                                  type: integer
                                  description: specify versions range
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                      required:
                        - within
                    - type: object
                      title: not_within
                      properties:
                        not_within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: versions
                              properties:
                                versions:
                                  type: integer
                                  description: specify versions range
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                      required:
                        - not_within
                product_version:
                  type: object
                  oneOf:
                    - type: object
                      title: greater_equal
                      properties:
                        greater_equal:
                          type: string
                          maxLength: 255
                      required:
                        - greater_equal
                    - type: object
                      title: greater_than
                      properties:
                        greater_than:
                          type: string
                          maxLength: 255
                      required:
                        - greater_than
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                    - type: object
                      title: less_equal
                      properties:
                        less_equal:
                          type: string
                          maxLength: 255
                      required:
                        - less_equal
                    - type: object
                      title: less_than
                      properties:
                        less_than:
                          type: string
                          maxLength: 255
                      required:
                        - less_than
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: within
                      properties:
                        within:
                          type: object
                          properties:
                            versions:
                              type: integer
                              description: versions range
                              minimum: 1
                              maximum: 65535
                              default: 1
                          required:
                            - versions
                      required:
                        - within
                    - type: object
                      title: not_within
                      properties:
                        not_within:
                          type: object
                          properties:
                            versions:
                              type: integer
                              description: versions range
                              minimum: 1
                              maximum: 65535
                              default: 1
                          required:
                            - versions
                      required:
                        - not_within
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                real_time_protection:
                  enum:
                    - 'no'
                    - 'yes'
                    - not-available
                  description: real time protection
                last_scan_time:
                  type: object
                  oneOf:
                    - type: object
                      title: not_available
                      properties:
                        not_available:
                          type: object
                      required:
                        - not_available
                    - type: object
                      title: within
                      properties:
                        within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: hours
                              properties:
                                hours:
                                  type: integer
                                  description: specify time in hours
                                  minimum: 1
                                  maximum: 65535
                                  default: 24
                      required:
                        - within
                    - type: object
                      title: not_within
                      properties:
                        not_within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: hours
                              properties:
                                hours:
                                  type: integer
                                  description: specify time in hours
                                  minimum: 1
                                  maximum: 65535
                                  default: 24
                      required:
                        - not_within
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                description: Product name
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        disk_backup:
          type: object
          properties:
            criteria:
              type: object
              properties:
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                last_backup_time:
                  type: object
                  oneOf:
                    - type: object
                      title: not_available
                      properties:
                        not_available:
                          type: object
                      required:
                        - not_available
                    - type: object
                      title: within
                      properties:
                        within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: hours
                              properties:
                                hours:
                                  type: integer
                                  description: specify time in hours
                                  minimum: 1
                                  maximum: 65535
                                  default: 24
                      required:
                        - within
                    - type: object
                      title: not_within
                      properties:
                        not_within:
                          type: object
                          oneOf:
                            - type: object
                              title: days
                              properties:
                                days:
                                  type: integer
                                  description: specify time in days
                                  minimum: 1
                                  maximum: 65535
                                  default: 1
                            - type: object
                              title: hours
                              properties:
                                hours:
                                  type: integer
                                  description: specify time in hours
                                  minimum: 1
                                  maximum: 65535
                                  default: 24
                      required:
                        - not_within
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                description: Product name
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        disk_encryption:
          type: object
          properties:
            criteria:
              type: object
              description: Encryption locations
              properties:
                is_installed:
                  type: boolean
                  description: Is Installed
                  default: true
                encrypted_locations:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Encryption location
                        maxLength: 1023
                      encryption_state:
                        type: object
                        oneOf:
                          - type: object
                            title: is
                            properties:
                              is:
                                enum:
                                  - encrypted
                                  - unencrypted
                                  - partial
                                  - unknown
                                default: encrypted
                          - type: object
                            title: is_not
                            properties:
                              is_not:
                                enum:
                                  - encrypted
                                  - unencrypted
                                  - partial
                                  - unknown
                                default: encrypted
                    required:
                      - name
            vendor:
              type: array
              description: Vendor name
              items:
                type: object
                description: Product name
                properties:
                  name:
                    type: string
                    maxLength: 103
                  product:
                    type: array
                    items:
                      type: string
                      pattern: .*
                      maxLength: 1023
                required:
                  - name
            exclude_vendor:
              type: boolean
              default: false
        custom_checks:
          type: object
          properties:
            criteria:
              type: object
              properties:
                process_list:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Process Name
                        maxLength: 1023
                      running:
                        type: boolean
                        default: true
                    required:
                      - name
                registry_key:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Registry key
                        maxLength: 1023
                      default_value_data:
                        type: string
                        description: Registry key default value data
                        pattern: .*
                        maxLength: 1024
                      negate:
                        type: boolean
                        description: Key does not exist or match specified value data
                        default: false
                      registry_value:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Registry value name
                              maxLength: 1023
                            value_data:
                              type: string
                              description: Registry value data
                              pattern: .*
                              maxLength: 1024
                            negate:
                              type: boolean
                              description: Value does not exist or match specified value data
                              default: false
                          required:
                            - name
                    required:
                      - name
                plist:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Preference list
                        maxLength: 1023
                      negate:
                        type: boolean
                        description: Plist does not exist
                        default: false
                      key:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Key name
                              maxLength: 1023
                            value:
                              type: string
                              description: Key value
                              pattern: .*
                              maxLength: 1024
                            negate:
                              type: boolean
                              description: Value does not exist or match specified value data
                              default: false
                          required:
                            - name
                    required:
                      - name
          required:
            - criteria
        mobile_device:
          type: object
          properties:
            criteria:
              type: object
              properties:
                jailbroken:
                  type: boolean
                  description: If device is by rooted/jailbroken
                disk_encrypted:
                  type: boolean
                  description: If device's disk is encrypted
                passcode_set:
                  type: boolean
                  description: If device's passcode is present
                last_checkin_time:
                  type: object
                  oneOf:
                    - type: object
                      title: within
                      properties:
                        within:
                          type: object
                          properties:
                            days:
                              type: integer
                              description: specify time in days
                              minimum: 1
                              maximum: 365
                              default: 30
                          required:
                            - days
                      required:
                        - within
                    - type: object
                      title: not_within
                      properties:
                        not_within:
                          type: object
                          properties:
                            days:
                              type: integer
                              description: specify time in days
                              minimum: 1
                              maximum: 365
                              default: 30
                          required:
                            - days
                      required:
                        - not_within
                imei:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                model:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                phone_number:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                tag:
                  type: object
                  oneOf:
                    - type: object
                      title: contains
                      properties:
                        contains:
                          type: string
                          maxLength: 255
                      required:
                        - contains
                    - type: object
                      title: is
                      properties:
                        is:
                          type: string
                          maxLength: 255
                      required:
                        - is
                    - type: object
                      title: is_not
                      properties:
                        is_not:
                          type: string
                          maxLength: 255
                      required:
                        - is_not
                applications:
                  type: object
                  properties:
                    has_malware:
                      type: object
                      oneOf:
                        - type: object
                          title: 'no'
                          properties:
                            'no':
                              type: object
                        - type: object
                          title: 'yes'
                          properties:
                            'yes':
                              type: object
                              properties:
                                excludes:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      name:
                                        type: string
                                        maxLength: 31
                                      package:
                                        type: string
                                        description: application package name
                                        pattern: .*
                                        maxLength: 1024
                                      hash:
                                        type: string
                                        description: application hash
                                        pattern: .*
                                        maxLength: 1024
                                    required:
                                      - name
                    has_unmanaged_app:
                      type: boolean
                      description: Has apps that are not managed
                    includes:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            maxLength: 31
                          package:
                            type: string
                            description: application package name
                            pattern: .*
                            maxLength: 1024
                          hash:
                            type: string
                            description: application hash
                            pattern: .*
                            maxLength: 1024
                        required:
                          - name
        certificate:
          type: object
          properties:
            criteria:
              type: object
              properties:
                certificate_profile:
                  type: string
                  description: Profile for authenticating client certificates
                  x-panMemberOf:
                    - location: shared
                      schema: certificate-profile
                      subPath: name
                certificate_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Attribute Name
                      value:
                        type: string
                        description: Key value
                        pattern: .*
                        maxLength: 1024
                    required:
                      - name
      oneOf:
        - type: object
          title: folder
          properties:
            folder:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The folder in which the resource is defined
              example: My Folder
          required: 
            -  folder
        - type: object
          title: snippet
          properties:
            snippet:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The snippet in which the resource is defined
              example: My Snippet
          required: 
            -  snippet
        - type: object
          title: device
          properties:
            device:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The device in which the resource is defined
              example: My Device
          required: 
            -  device
    hip-profiles:
      type: object
      required:
        - id
        - name
        - match
      properties:
        id:
          type: string
          description: UUID of the resource
          readOnly: true
          example: 123e4567-e89b-12d3-a456-426655440000
        name:
          type: string
          pattern: ^[ a-zA-Z\d.-_]+$
          description: The name of the HIP profile
          maxLength: 31
        description:
          type: string
          maxLength: 255
        match:
          type: string
          maxLength: 2048
      oneOf:
        - type: object
          title: folder
          properties:
            folder:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The folder in which the resource is defined
              example: My Folder
          required: 
            -  folder
        - type: object
          title: snippet
          properties:
            snippet:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The snippet in which the resource is defined
              example: My Snippet
          required: 
            -  snippet
        - type: object
          title: device
          properties:
            device:
              type: string
              pattern: ^[a-zA-Z\d-_\. ]+$
              maxLength: 64
              description: The device in which the resource is defined
              example: My Device
          required: 
            -  device
```
